Login screen
AGES-PUCRS/simulados-front-user pull request #10
Opened 2018-09-28 04:43 UTC by edornelles1992

Tela inicial para logar no app.
Deixei as telas Examples e ViewAnswers fora do ProtectedRoute. As demais estão.
Coloquei a tela de login na '/' e passei o menu inicial para '/dashboard'.

2018-09-28 12:56 UTC, renanpvaz requested changes

2018-09-28 12:56 UTC, renanpvaz commented on src/components/Layout/index.js
> +        {location.pathname === '/' ? null : <Header />}
Esssa lógica não é necessária, é só organizar as rotas assim:

```
<Switch>
  <Layout>
    <Route />
    <Route />
    ...
  </Layout>
  <Route component={Login} />
</Switch>
```

2018-09-28 12:56 UTC, renanpvaz commented on src/containers/ProtectedRoute/index.js
> +    const user = getData(state)
Essa lógica poderia ser um selector em si `isAllowed : state -> bool`

2018-09-28 12:56 UTC, renanpvaz commented on src/scenes/Login/index.js
> +    if (email.length <= 0 || password.length <= 0) {
Para fazer essa validação você poderia usar um `<Form onSubmit={...} />` e colocar `required` em todos os inputs. Assim tu tira o `onClick` do botao e bota `type="submit"` nele. Desse jeito o form vai usar a validação de campo nativa e vai funcionar com enter também.

2018-09-29 15:20 UTC, edornelles1992 commented on src/components/Layout/index.js
> +        {location.pathname === '/' ? null : <Header />}
Então, eu tentei dessa maneira, porém assim a rota de login não renderiza, sabe o que pode ser?

2018-10-01 11:41 UTC, renanpvaz requested changes

2018-10-01 11:41 UTC, renanpvaz commented on src/scenes/Login/index.js
> +    event.preventDefault()
Dá para usar o componente`<Form />` que já previne o refresh pra ti.

2018-10-01 11:41 UTC, renanpvaz commented on src/index.js
> +            <Route exact path="*" render={() => 404} />
exact com path * não vai funcionar provavelmente.

2018-10-01 11:41 UTC, renanpvaz commented on src/index.js
> +            <Route exact path="/" component={Login} />
Acho que o path poderia ser "/login" mesmo, o componente ProtectedRoute poderia redirecionar para este caminho daí.

2018-10-01 11:41 UTC, renanpvaz commented on src/index.js
> +            <Route exact path="/" component={Login} />
Se esta rota, ou outras, não estavam renderizando tem que conectar o componente layout para escutar as atualizacoes do router: https://github.com/AGES-PUCRS/simulados-front-admin/blob/dev/src/App.js#L20

2018-10-02 13:01 UTC, renanpvaz requested changes

2018-10-02 13:01 UTC, renanpvaz commented on src/scenes/Login/index.js
> +  async onPressEnter(event) {
Se tu declarar este método como arrow function tu pode passar ele direto para o handler:
```
async onPressEnter = () => {
  ...
}
```
```
onSubmit={this.onPressEnter}
```

2018-10-02 13:01 UTC, renanpvaz commented on src/store/user/actions.js
> +const logout = () => dispatch => {
O logout não precisa ser um thunk, ele pode ser uma ação normal pois não está fazendo nada assíncrono. É só usar a action userLogout diretamente.

2018-10-02 13:01 UTC, renanpvaz commented on src/scenes/Login/index.js
> +    this.props.logout()
Acho que só precisamos fazer o logout se o usuário estiver logado e clicar no botão para deslogar. Neste caso por enquanto não precisamos fazer nada.

2018-10-02 13:01 UTC, renanpvaz commented on src/store/user/actions.js
> +const fetchAuth = (email, password) => dispatch => {
Acho que  esta action podemos chamar de `login` só. Especialmente considerando que é um post (cria um recurso) invés de buscar algo.

2018-10-03 23:08 UTC, renanpvaz approved these changes

2018-10-05 19:27 UTC, merged