Confirmar resposta
AGES-PUCRS/simulados-front-user pull request #12
Opened 2018-10-23 13:52 UTC by homerooliveira

2018-10-23 14:00 UTC, renanpvaz requested changes

2018-10-23 14:00 UTC, renanpvaz commented on src/scenes/Exam/index.js
> +    let alternativeId = event.target.id
Acho que esta não é a melhor forma de obter o id da alternativa, o RadioGroup deveria chamar o onChange enviando a option selecionada, aí bastava tu pegar o value dela.

2018-10-23 14:04 UTC, homerooliveira commented on src/scenes/Exam/index.js
> +    let alternativeId = event.target.id
Mudar o RadioGroup então?

2018-10-23 14:09 UTC, homerooliveira commented on src/scenes/Exam/index.js
> +    let alternativeId = event.target.id
```javascript
onChange={event => onChange(event.target.id)}
```
colocar isso no Radio?

2018-10-24 18:25 UTC, renanpvaz requested changes

2018-10-24 18:25 UTC, renanpvaz commented on src/components/RadioGroup/index.js
> +      onChange={event => onChange(event.target.id)}
Não era exatamente isso que quis dizer, o problema é ter que acessar o target para pegar o id enquanto tu ja tem o valor disponível no escopo. Nesses casos com componentes com opções o padrão é enviar a opção selecionada no evento de change. Acho que o `<Radio>` tem de passar a receber a função de `onChange` e p `<RadioGroup>` deveria passar: ```onChange={() => onChange(option)}```. Assim será necessário alterar os lugares que usam o radio, porque o evento não será passado mais, e sim a option.

2018-10-25 00:12 UTC, renanpvaz approved these changes

2018-10-25 13:05 UTC, merged