Tela do resultado do simulado
AGES-PUCRS/simulados-front-user pull request #14
Opened 2018-10-26 00:59 UTC by gregslag

Segue a tela do resultado do simulado. Como não estou recebendo o id da participação ainda, basta alterar o parâmetro do fetchResult (componentDidMount) para 1, 2 ou 3 para testar com os dados da nossa base.

2018-10-30 00:23 UTC, renanpvaz requested changes

2018-10-30 00:23 UTC, renanpvaz commented on src/components/CardQuestion/cardQuestion.scss
> +.card {
Esse seletor irá afetar todos os cards, não apenas os CardQuestion. Sugiro usar um nome único baseado no nome do componente: card-question.

2018-10-30 00:23 UTC, renanpvaz commented on src/components/CardQuestion/cardQuestion.scss
> +  -moz-box-shadow: 0px 3px 7px 0px rgba(0, 0, 0, 0.75);
Não é necessário usar os vendor prefixes porque existe um plugin de postcss que faz isso pra nós no projeto.

2018-10-30 00:23 UTC, renanpvaz commented on src/components/CardQuestion/cardQuestion.scss
> +  &-expanded {
Na convenção BEM os modificadores são demarcados por `--`. http://getbem.com/introduction/

2018-10-30 00:23 UTC, renanpvaz commented on src/components/CardQuestion/cardQuestion.scss
> +  & .toggleQuestions {
Neste caso, também usando BEM, acredito que esta classe deveria ser um elemento do card question usando o `__` como notação.

2018-10-30 00:23 UTC, renanpvaz commented on src/components/CardQuestion/index.js
> +    this.state = { toogleArea: false }
O ideal é que o estado não vivesse neste componente, mas sim em quem o usa. Desta forma o componente receberia essa informação como prop e poderia ser um componente funcional simples.

https://reactjs.org/docs/lifting-state-up.html

2018-10-30 00:23 UTC, renanpvaz commented on src/components/CardQuestion/index.js
> +        onClick={this.showQuestions.bind(this)}
Neste caso não é necessário o bind, basta chamar o método dentro de uma arrow function (que atribui ao contexto atual do this) ou, melhor ainda, fazer o seguinte: 
```
showQuestions = () => { // declarando o método assim ele não perderá a referência ao contexto da classe
  ...
}
...
onClick={this.showQuestions} // basta apenas passar o método sem bind e sem arrow function
```

2018-10-30 00:23 UTC, renanpvaz commented on src/components/CardQuestion/index.js
> +import './cardQuestion.scss'
Acho que o nome do arquivo deveria ser em lisp-case para seguir o padrão dos outros.

2018-10-30 00:23 UTC, renanpvaz commented on src/components/CardQuestion/cardQuestion.scss
> +    & .toggleQuestions {
Classes também deveriam seguir o padrão de lisp-case para uniformidade.

2018-10-30 00:23 UTC, renanpvaz commented on src/components/Score/index.js
> +      title ? <h3>{this.getMessage(hits, total)}</h3> : ''
Quando apenas um dos casos do ternário for renderizar algo é só usar o operador curto-circuito: 
```title && <h3>...</h3>```

2018-10-30 00:23 UTC, renanpvaz commented on src/components/Score/index.js
> +        <SubTitle />
Outra observação é que este tipo de coisa da pra fazer inline mesmo, não tem necessidade de criar um componente dentro do método:
```diff
- <SubTitle />
+ {title && <h3>{this.getMessage(hits, total)}</h3>}
```

2018-10-30 00:23 UTC, renanpvaz commented on src/components/Score/score.scss
> +  &-green {
Mesmo ponto sobre modificadores.

2018-10-30 00:23 UTC, renanpvaz commented on src/components/Score/score.scss
> +  padding: 0 !important;
O important! nunca é ideal, foi corrigido em outra branch a prioridade de carregamento dos estilos então o card não iria sobrescrever o estilo. Podemos manter assim por enquanto.

2018-10-30 00:23 UTC, renanpvaz commented on src/index.js
> +              <ProtectedRoute exact path="/result" component={Result} />
Como vai fazer parte da url acho que deveria ser em português.

2018-10-30 00:23 UTC, renanpvaz commented on src/scenes/Result/index.js
> +      .then(this.extractData.bind(this))
Mesma situação do .bind antes comentada

2018-10-30 00:23 UTC, renanpvaz commented on src/scenes/Result/index.js
> +      this.props.data.result.map(r => {
O map neste caso está sendo usado como um .forEach, ou seja, não está retornando nada.

[map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) vs [forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach)

2018-10-30 00:23 UTC, renanpvaz commented on src/scenes/Result/index.js
> +  getTime(time) {
Isto poderia ser um utilitário na pasta /utils

2018-10-30 00:23 UTC, renanpvaz commented on src/scenes/Result/index.js
> +            getTime={this.getTime}
Invés de passar a função com este propósito, é mais fácil passar o resultado (a string) diretamente.

2018-10-30 00:23 UTC, renanpvaz commented on src/scenes/Result/index.js
> +        <br />
O ideal é evitarmos ```<br>``` para espaçamento: difícil de depurar e controlar o tamanho. Aconselho usar uma das classes "space-stack-[tamanho]" localizadas em _spacing.scss

2018-11-16 16:41 UTC, gregslag commented on src/components/CardQuestion/cardQuestion.scss
> +.card {
Alterei o seletor para card-question como sugerido.

2018-11-16 16:42 UTC, gregslag commented on src/components/CardQuestion/cardQuestion.scss
> +  -moz-box-shadow: 0px 3px 7px 0px rgba(0, 0, 0, 0.75);
Não sabia da existência do plugin, resolvido!

2018-11-16 16:42 UTC, gregslag commented on src/components/CardQuestion/cardQuestion.scss
> +  &-expanded {
Não conhecia a convenção BEM.. Valeu pela dica!

2018-11-16 16:42 UTC, gregslag commented on src/components/CardQuestion/cardQuestion.scss
> +  & .toggleQuestions {
Ajustado conforme sugerido!

2018-11-16 16:43 UTC, gregslag commented on src/components/CardQuestion/index.js
> +import './cardQuestion.scss'
Ajustado para lisp-case!

2018-11-16 16:43 UTC, gregslag commented on src/components/CardQuestion/cardQuestion.scss
> +    & .toggleQuestions {
Ajustado para lisp-case!

2018-11-16 16:44 UTC, gregslag commented on src/components/Score/index.js
> +      title ? <h3>{this.getMessage(hits, total)}</h3> : ''
Modificado para usar o operador curto-circuito!

2018-11-16 16:45 UTC, gregslag commented on src/components/Score/index.js
> +        <SubTitle />
Removi o componente interno e renderizei diretamente como sugerido!

2018-11-16 16:45 UTC, gregslag commented on src/components/Score/score.scss
> +  &-green {
Ajustado para convenção BEM!

2018-11-16 16:46 UTC, gregslag commented on src/components/Score/score.scss
> +  padding: 0 !important;
Desculpe, não entendi muito bem... Devo remover o important?

2018-11-16 16:46 UTC, gregslag commented on src/index.js
> +              <ProtectedRoute exact path="/result" component={Result} />
Traduzido para português!

2018-11-16 16:46 UTC, gregslag commented on src/scenes/Result/index.js
> +      .then(this.extractData.bind(this))
Alterei o escopo da função e removi o bind.

2018-11-16 16:47 UTC, gregslag commented on src/scenes/Result/index.js
> +      this.props.data.result.map(r => {
Alterei o map para o forEach como sugerido

2018-11-23 19:31 UTC, gregslag commented on src/components/CardQuestion/index.js
> +    this.state = { toogleArea: false }
Alterado o estado do componente para ser recebido por props

2018-11-23 19:32 UTC, gregslag commented on src/components/CardQuestion/index.js
> +        onClick={this.showQuestions.bind(this)}
Como o componente não possui mais o estado, a função foi removida

2018-11-23 19:47 UTC, gregslag commented on src/scenes/Result/index.js
> +            getTime={this.getTime}
Função getTime movida para a pasta utils

2018-11-23 19:57 UTC, gregslag commented on src/scenes/Result/index.js
> +        <br />
<br> removidos e classe "space-stack-xl" utilizada

2018-11-23 19:57 UTC, gregslag commented on src/scenes/Result/index.js
> +  getTime(time) {
função getTime movida para a pasta utils

2018-11-23 21:28 UTC, fabiohsalmeida approved these changes

2018-11-23 22:41 UTC, merged