Menu screen
AGES-PUCRS/simulados-front-user pull request #5
Opened 2018-09-14 04:21 UTC by edornelles1992

task: Implementar tela de menu, com opção de novo simulado

2018-09-14 16:20 UTC, renanpvaz requested changes

2018-09-14 16:20 UTC, renanpvaz commented on src/components/Container/container.scss
> +    padding: 0 0px;
Esta regra não está fazendo nada pois você já havia removido o padding do .container. Aquele padding (este também) é necessário para que tenha um espaço entre o conteudo e o limite do viewport, sem ele você teve de definir margin e padding no eixo x para todos os elementos do conteúdo usados (header, h1, h6 e cards).

2018-09-14 16:20 UTC, renanpvaz commented on src/components/Icon/index.js
> +Icon.defaultProps = {
Quando o componente for função não precisamos definir os valores default assim, basta defini-los no argumento: 
```
const Icon = ({ name = '', height = 16, width = 16, color = 'black' }) => (
```
Outro detalhe é que não devíamos usar valores específicos como padrões.

2018-09-14 16:20 UTC, renanpvaz commented on src/components/MenuCard/index.js
> +class MenuCard extends Component {
Como este componente não usa nenhum método de ciclo de vida e nem possui estado interno, não há necessidade de defini-lo como classe.

2018-09-14 16:20 UTC, renanpvaz commented on src/components/MenuCard/index.js
> +      <Card className="card">
A prop className não é necessária pois o card já utiliza esta classe.

2018-09-14 16:20 UTC, renanpvaz commented on src/components/MenuCard/index.js
> +      blueContainer,
Acho que com parâmetros booleanos para cada cor ficaria difícil usar várias cores diferentes e alterá-las com facilidade. Sugiro que receba a cor assim como o ícone já faz.

2018-09-14 16:20 UTC, renanpvaz commented on src/components/MenuCard/index.js
> +  label: 'lorem ipsum',
Mesma questão das props default sendo específicas. Lembrando que não precisamos definir valores default para todas elas.

2018-09-14 16:20 UTC, renanpvaz commented on src/components/MenuCard/index.js
> +  onClick: () => {},
Quando o callback passado para o React é `undefined` ele só ignora, se não me engano.

2018-09-14 16:20 UTC, renanpvaz commented on src/components/MenuCard/menucard.scss
> +.card {
Esta regra, apesar de definida neste arquivo, irá modificar todos os cards exibidos. Caso as propriedades definidas façam sentido para todo e qualquer card, podemos alterar direto no arquivo de estilo do card. Sendo uma regra com propriedades específicas o ideal é criar outra classe e usá-la em conjunto. Exemplo: 
```
// js
<Card className="my-specific-variation-of-card" />

// sass
.my-specific-variation-of-card {
  // propriedades especificas
}
```

2018-09-14 16:20 UTC, renanpvaz commented on src/components/MenuCard/menucard.scss
> +.text {
Esta classe, apesar de possuir um nome genérico, possui propriedades específicas também que não vão fazer sentido em outros contextos. Minha sugestão é usar a notação de Element do [BEM](http://getbem.com/introduction/). O mesmo vale para as outras classes: 
```
.menucard {
  ...
}

.menucard__button {  //no lugar de cardButton
  ...
}

.menucard__text {  //no lugar de text
  ...
}

.menucard__icon {  //no lugar de iconContainer
  ...
}
```
Assim `.menucard` é o bloco e todos começando com '__' (dois underlines) são elementos do mesmo. Desta forma sabemos que estes estilos não vão entrar em conflito com outros da aplicação.

2018-09-14 16:20 UTC, renanpvaz commented on src/index.js
> +            <Route path="/dashboard" component={Dashboard} />
Acho que esta pode passar a ser a tela inicial e os exemplos podem ficar em /exemplos agora.

2018-09-14 16:20 UTC, renanpvaz commented on src/scenes/Dashboard/dashboard.scss
> +.mainContainer {
Acho que esta regra é desnecessária: a cor era apenas a cor padrão da ferramenta de mockup e a altura não precisa ser limitada para que o conteúdo possa crescer normalmente.

2018-09-14 16:20 UTC, renanpvaz commented on src/index.scss
> +  max-width: 1000px;
Acho que este estilo poderia ser definido diretamente no Container/container.scss (substituindo os 700px). Além disso, o tamanho usado no protótipo foi 980px, que é um dos tamanhos padrão para conteúdo da página.

2018-09-14 16:20 UTC, renanpvaz commented on src/scenes/Dashboard/dashboard.scss
> +.title {
Aqui eu dou a mesma sugestão sobre nomenclatura das classes para evitarmos conflitos e sobrescritas: http://getbem.com/.

2018-09-14 16:20 UTC, renanpvaz commented on src/scenes/Dashboard/dashboard.scss
> +  padding: 30px 10px 0px;
Aqui o padding para o eixo x vai deixar de ser necessário caso o `.container` volte a ter o padding padrão. O alinhamento não precisa ser definido pois já é o padrão. Se for necessário usar outro alinhamento já existem em stylesheets/utilities/_align.scss.

2018-09-14 16:20 UTC, renanpvaz commented on src/scenes/Dashboard/dashboard.scss
> +.description {
Mesmos pontos anteriores.

2018-09-14 16:20 UTC, renanpvaz commented on src/scenes/Dashboard/index.js
> +import MenuCard from '../../components/MenuCard'
Existem aliases definidos para todas as pastas diretamente dentro de /src, então os imports podem ficar apenas:
```
import TalCoisa from 'components/TalCoisa' 
import talOutraCoisa from 'store/ui/talOutraCoisa'
import TalOutraOutraCoisa from 'containers/TalOutraOutraCoisa'
```

2018-09-14 16:20 UTC, renanpvaz commented on src/services/ExamService.js
> +export default class ExamService {
Acho legal a ideia das services mas neste caso esta parte deveria ser governada pelo redux, se tu estiveres com dificuldade com esta parte posso te ajudar ou podemos refatorar depois.

2018-09-14 16:20 UTC, renanpvaz commented on src/components/MenuCard/menucard.scss
> +  margin-left: 82%;
Este tipo de propriedade é bem perigosa porque pode quebrar com qualquer variação do viewport ou do tamanho dos elementos. O mesmo vale para os usos aqui de `top`, `bottom` e especialmente `float`. Minha sugestão seria usar dos utilitários que já existem em stylesheets/utilities/, pois nos casos triviais estes devem ser suficiente. No componente poderia ficar organizado assim:
```
<Card className="flex items-center justify-between">
  <div class="flex space-between-inline-m">
    <div class="iconContainer">
      <Icon 
        className="center-vertically" 
        name={icon} 
        height={30} 
        width={30} 
        color={iconColor} 
      />
    </div>
    <div>
      <h3 class="space-stack-s">Simular Prova</h3>
      <p>Selecione e execute uma prova dos anos anteriores</p>
    </div>
  </div>
</Card>
```
Recursos relevantes: [Basic concepts of flexbox](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox) e [Space in design systems](https://medium.com/eightshapes-llc/space-in-design-systems-188bcbae0d62).

2018-09-14 16:20 UTC, renanpvaz commented on src/components/header/index.js
> +class Header extends Component {
Acredito que o header não está de acordo com o protótipo, porém o mesmo não está no escopo da tarefa, então pode ser feito (ou refeito) noutro momento.

2018-09-15 16:20 UTC, edornelles1992 commented on src/components/header/index.js
> +class Header extends Component {
Sim, eu acabei fazendo só um esboço dele como estava nos mockups, vou retirar das telas. compensa eu deixar a classe no projeto pra ser melhorada depois?

2018-09-15 18:21 UTC, renanpvaz commented on src/components/header/index.js
> +class Header extends Component {
Claro, não vejo problemas, tu que sabe.

2018-09-16 16:14 UTC, renanpvaz requested changes

2018-09-16 16:14 UTC, renanpvaz commented on src/components/MenuCard/index.js
> +    <div class="flex menucard__innercontainer">
Acho que no meu exemplo coloquei errado, deixei `class` em vez de `className`. Não queria comentar mais nada, mas acho que isso talvez não funcione porque `class` é uma palavra reservada.

2018-09-16 16:15 UTC, renanpvaz commented on src/components/MenuCard/index.js
> +    <div class="flex menucard__innercontainer">
O resto está ótimo tho, vi o preview e a tela continua fiel.
 🎉🎉🎉

2018-09-16 16:38 UTC, edornelles1992 commented on src/components/MenuCard/index.js
> +    <div class="flex menucard__innercontainer">
hahaha tranquilo. Funciona com class sim, acabei descobrindo pegando o exemplo que vc tinha passado hahah, mas vou trocar pra ficar no padrão correto.

2018-09-16 17:25 UTC, renanpvaz approved these changes
👌

2018-09-17 11:46 UTC, merged