Visualizacao respostas
AGES-PUCRS/simulados-front-user pull request #6
Opened 2018-09-20 00:10 UTC by guidraghetti

Tela de visualização de respostas e comentários de uma questão.
work in progress: tela depende da API para requisitar os estados.

2018-09-21 04:33 UTC, IsraelDeorce commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implementar tela de visualização de questão durante simulado](https://trello.com/c/qXunxb7I/48-implementar-tela-de-visualiza%C3%A7%C3%A3o-de-quest%C3%A3o-durante-simulado)

2018-09-21 04:35 UTC, IsraelDeorce commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implementar tela de visualização de questão durante simulado](https://trello.com/c/qXunxb7I/48-implementar-tela-de-visualiza%C3%A7%C3%A3o-de-quest%C3%A3o-durante-simulado)

2018-09-21 04:37 UTC, IsraelDeorce commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implementar tela de visualização de respostas e comentários durante um simulado](https://trello.com/c/mtiCYoKv/49-implementar-tela-de-visualiza%C3%A7%C3%A3o-de-respostas-e-coment%C3%A1rios-durante-um-simulado)

2018-09-21 04:52 UTC, IsraelDeorce commented
@guidraghetti, copiando o e-mail do @renanpvaz : 
"sua branch está conflitando. Rode git pull --rebase origin dev, vão aparecer que certos arquivos estão com conflito, então resolva todos os conflitos de cada passo e então rode git add . e depois git rebase --continue. Itere nesse último passo até que o rebase termine e depois execute git push --force-with-lease.

Uma dica, quando houverem conflitos o terminal vai exibir entre varias mensagens os caminhos dos arquivos com conflitos, algo tipo:
...
CONFLICT: app/routes/user.js
CONFLICT: server.js
...
"

2018-09-21 13:44 UTC, renanpvaz requested changes

2018-09-21 13:44 UTC, renanpvaz commented on src/scenes/ViewAnswers/index.js
> +    return correct === userAnswer
Acho que isto poderia ser simplificado com: ```this.setState({ viewAnswers: correct === userAnswer })```

2018-09-21 13:44 UTC, renanpvaz commented on src/scenes/ViewAnswers/index.js
> +export default connect(
Não precisa do connect já que o growl (ou outras actions) não são usadas, poderia ficar: 
```export default ViewAnswers```

2018-09-21 13:44 UTC, renanpvaz commented on src/scenes/ViewAnswers/viewAnswers.scss
> +.rightAnswer {
Aqui é uma situação onde poderia usar [BEM](http://getbem.com/introduction/). Ficaria algo tipo:
```
.answer {
  // estilos da comuns às duas (ou o padrão poderia ser a errada)

  &--right {
    // estilos da correta
   }

  &--wrong {
    // estilos da errada
   }
}
```
E para usar seria:
```
<div className="answer answer--wrong"></div>
```

2018-09-21 13:44 UTC, renanpvaz commented on src/scenes/ViewAnswers/viewAnswers.scss
> +.nextQuestion {
Acho que esta classe não está sendo usada.

2018-09-21 13:44 UTC, renanpvaz commented on src/scenes/ViewAnswers/viewAnswers.scss
> +  margin: 3%;
Acho que esses espaçamentos não são necessários. Use um ```<Container />``` em volta do conteúdo e os utilitários de stylesheets/utilities/_spacing.scss para outros espaços que tu precisar.

2018-09-21 13:44 UTC, renanpvaz commented on src/scenes/ViewAnswers/index.js
> +import { GROWL_INFO, GROWL_ERROR, GROWL_SUCCESS } from 'store/ui/constants'
Esses dois imports não são necessários.

2018-09-21 13:44 UTC, renanpvaz commented on src/scenes/ViewAnswers/index.js
> +import './viewAnswers.scss'
normalmente os arquivos nomeamos com snake-case: minúsculo separado por traços.

2018-09-22 15:46 UTC, renanpvaz requested changes
Acho que só mais estes pontos e podemos aceitar.

2018-09-22 15:46 UTC, renanpvaz commented on src/scenes/ViewAnswers/index.js
> +          <p className="spacing space-x-m">{this.state.coments}</p>
Esta classe spacing não existe, basta usar direto a classe desejada, tu pode ver todas elas no arquivo _spacing.scss.

2018-09-22 15:46 UTC, renanpvaz commented on src/scenes/ViewAnswers/index.js
>      const { userAnswer } = this.state
Aqui tu pode fazer o destructuring numa linha só: ```const { correct, userAnswer } = this.state```

2018-09-25 00:17 UTC, renanpvaz approved these changes

2018-09-25 11:17 UTC, fabiohsalmeida approved these changes

2018-09-25 12:28 UTC, merged